import type { Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: 1,
    name: "Sales Analytics & Strategy",
    role: "Data Analyst",
    skills: [
      "SQL",
      "Python",
      "Excel",
      "Tableau",
      "Power BI",
      "Google Analytics",
      "Statistics",
    ],
    client: "Circle K Esso",
    points: [
      "Researched and analyzed monthly sales trends by region, product category, and customer demographics to identify slow-moving inventory and strategic improvement opportunities.",
      "Flagged underperforming SKUs accounting for ~10% of total inventory; supported category managers in data-informed repricing, improving category-level sales by 3–5%.",
      "Identified seasonal demand patterns, market drivers, and pricing sensitivities, refining promotional strategies and timing for key product groups.",
      "Built structured performance reports to track product sell-through and inventory aging, enabling data-backed strategic planning and reducing stockouts in high-demand SKUs.",
      "Partnered with cross-functional teams (marketing, merchandising, strategy) to align insights with promotional campaigns, contributing to improved conversion rates in selected regions.",
    ],
    link: "",
  },
  {
    id: 2,
    name: "Healthcare Claims Pipeline",
    role: "Data Engineer",
    skills: [
      "Python",
      "SQL",
      "ETL",
      "Data Validation",
      "HIPAA Compliance",
      "Data Pipelines",
    ],
    client: "Edifecs",
    points: [
      "Cleaned and validated large volumes of U.S. healthcare claims data, improving accuracy and reliability for downstream reporting.",
      "Identified common data quality issues and supported enhancements that reduced recurring errors and manual corrections by approximately 11%.",
      "Ensured compliance with HIPAA and internal data handling standards, contributing to data integrity and audit-ready deliverables for analytical teams.",
    ],
    link: "",
  },
  {
    id: 3,
    name: "AI & Data Science Capstone",
    role: "Data Scientist",
    skills: [
      "Python",
      "TensorFlow",
      "scikit-learn",
      "Pandas",
      "NumPy",
      "NLP",
      "Deep Learning",
      "Jupyter",
    ],
    client: "Loyalist College",
    points: [
      "Developed and trained ML models for classification and clustering tasks using scikit-learn, TensorFlow, and PyTorch as part of an AI & Data Science postgraduate program.",
      "Applied NLP techniques and feature engineering to extract insights from unstructured text data, achieving high accuracy on benchmark datasets.",
      "Built end-to-end data pipelines from data acquisition through modeling and visualization, demonstrating full-cycle data science competency.",
      "Graduated with an 84.9 GPA and earned a place on the Dean's List for academic excellence.",
    ],
    link: "",
  },
  {
    id: 4,
    name: "Azure Cloud & Data Solutions",
    role: "Cloud Data Engineer",
    skills: [
      "Azure",
      "Docker",
      "Kubernetes",
      "Spark",
      "Hadoop",
      "Kafka",
      "Airflow",
      "Hive",
    ],
    client: "Microsoft Certified",
    points: [
      "Earned three Microsoft Azure certifications: Azure Data Fundamentals, Azure AI Fundamentals, and Azure Fundamentals.",
      "Designed and implemented data pipelines using Azure cloud services, integrating ETL workflows with Spark and Airflow for scalable data processing.",
      "Worked with big data technologies including Hadoop, Hive, and Kafka for real-time and batch data integration solutions.",
      "Containerized data applications with Docker and Kubernetes, enabling reproducible deployments and streamlined DevOps workflows.",
    ],
    link: "",
  },
];
